### ISSUE TITLE
Organized expenses missing couple entries

### ISSUE THREAD

**Issue by pjbrunner** [pbrunner/finance-visualizer#4]
Examining the resulting CSV from organize.py showed a couple of expense entries were wrongfully excluded. These entries share the same date with an entry that was intentionally excluded due to the exceptions file provided at runtime, perhaps that has something to do with it... It could also have to something do to with the fact that the income CSV was given first when running the script.

**Comment by pbrunner** [comment]
Resolved in commit 12fe882.

**Comment by pjbrunner** [comment]
Resolved in commit 1e1bf10.
